import { useState } from 'react';
import Head from 'next/head';
import Sidebar from '@/components/Sidebar';
import styles from '@/styles/Home.module.css';
import UploadButton from '../components/UploadButton';

export default function Home() {
  const [selectedFiles1, setSelectedFiles1] = useState(null);
  const [selectedFiles2, setSelectedFiles2] = useState(null);
  const [selectedFiles3, setSelectedFiles3] = useState(null);

  const handleUpload = (setSelectedFiles) => (selectedFiles) => {
    setSelectedFiles(selectedFiles);
    console.log(selectedFiles); // log selected files
  };

  const handleGenerateClick = () => {
    console.log("Generate button clicked");
    [selectedFiles1, selectedFiles2, selectedFiles3].forEach((selectedFiles, index) => {
      if (selectedFiles) {
        const formData = new FormData();
        Array.from(selectedFiles).forEach((file) => {
          formData.append('file', file);
        });
  
        fetch('/api/upload', {
          method: 'POST',
          body: formData,
        })
          .then(() => {
            if (index === 2) {
              fetch('/api/generate-schedule', { method: 'POST' })
                .then(() => console.log('main.py executed'))
                .catch(error => console.error(error));
            }
          })
          .catch(error => console.error(error));
      }
    });
  };

  const handleGenerateClick2 = () => {
    console.log("Generate button clicked");
    fetch('/api/generate-schedule', { method: 'POST' })
      .then(() => console.log('main.py executed'))
      .catch(error => console.error(error));
    }
  

  return (
    <div className="flex">
      <Head>
        <title>Switch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <main className="pl-64 flex-grow flex flex-col items-center justify-center h-screen space-y-4">
        <h1 className={styles.title}>Upload files</h1>
        <div className="flex space-x-4">
          <UploadButton onFilesSelect={handleUpload(setSelectedFiles1)} />
          <UploadButton onFilesSelect={handleUpload(setSelectedFiles2)} />
          <UploadButton onFilesSelect={handleUpload(setSelectedFiles3)} />
        </div>
        <button onClick={handleGenerateClick} className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-cyan-200 dark:focus:ring-cyan-800">
          <span className="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
            Upload
          </span>
        </button>

        <button onClick={handleGenerateClick2} className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-cyan-200 dark:focus:ring-cyan-800">
          <span className="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
            Generate
          </span>
        </button>
      </main>
    </div>
  );
}
