import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Sidebar from "@/components/Sidebar";
import UploadButton from "@/components/UploadButton";
import UploadQuintela from "@/components/UploadQuintela";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [selectedFiles, setSelectedFiles] = useState([]);

  const saveFiles = async (files) => {
    try {
      await fs.ensureDir("./mike"); // Cria a pasta ./mike se ela não existir
      files.forEach(async (file) => {
        await fs.copy(file.path, `./mike/${file.name}`); // Copia o arquivo para a pasta ./mike
      });
      console.log("Arquivos salvos com sucesso!");
    } catch (err) {
      console.error(err);
    }
  };

  const handleFilesSelect1 = (files) => {
    setSelectedFiles((prevSelectedFiles) => [...prevSelectedFiles, ...files]);
  };

  const handleFilesSelect2 = (files) => {
    setSelectedFiles((prevSelectedFiles) => [...prevSelectedFiles, ...files]);
  };

  const handleGenerateClick = () => {
    console.log(selectedFiles);
  };
  return (
    <>
      <Head>
        <title>Switch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar />

        <div className="flex flex-col p-4 justify-center bg-slate-200 sm:ml-64">
          <div className="flex flex-row">
            <span className="mb-4 text-2xl font-bold">Upload File</span>
            <div className="flex flex-row ml-auto">
              <button
                type="button"
                className="inline-flex items-center px-4 py-2 text-sm mb-4 font-medium text-white bg-blue-600 border border-transparent rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                onClick={handleGenerateClick}
              >
                Generate
              </button>
            </div>
          </div>

          <div className=" mr-auto w-[25%] p-4 rounded-lg dark:border-gray-700">
            <div className="grid grid-cols-3 gap-4 mb-4">
                
                <div className="flex items-center justify-center h-1 rounded dark:bg-gray-800">
                    <span>cenas</span>          
                </div>
                <div className="flex items-center justify-center h-1 rounded dark:bg-gray-800">
                    <span>cenas 2</span>           
                </div>
            </div>
          
            <div className="grid grid-cols-3 gap-4 mb-4">
                <div className="flex items-center justify-center h-24 rounded bg-gray-50 dark:bg-gray-800">
                    <UploadQuintela onFilesSelect={handleFilesSelect1} />              
                </div>
                <div className="flex items-center justify-center h-24 rounded bg-gray-50 dark:bg-gray-800">
                    <UploadQuintela onFilesSelect={handleFilesSelect1} />              
                </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
