import Image from "next/image";
import Head from "next/head";

import FooterComponent from "./components/footer";

function IndexPage() {
  return (
    <>
      <Head>
        <title>Switch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-white">
        <div className="bg-gradient-to-tr from-blue-200 to-blue-600 relative h-screen w-screen">
          <img
            className="absolute inset-0 w-full h-full object-cover mix-blend-multiply filter brightness-50"
            alt="main background image"
            src="https://www.teahub.io/photos/full/206-2064041_free-simple-wallpaper-backgrounds-for-your-desktop-simple.jpg"
          />

          <div className="absolute inset-0 flex flex-col justify-center items-center w-5/6 max-w-lg mx-auto text-center">
            <div className="space-y-8">
              <div className="flex justify-center items-center">
                <Image
                  alt="necc-logo"
                  src="/logos/necc-white.svg"
                  width={50}
                  height={50}
                />
              </div>
              <h1 className="font-primary font-extrabold text-3xl sm:text-4xl md:text-5xl md:leading-tight">
                Easily switch shifts on{" "}
                <span className="text-palette-primary">NameAPP.</span>
              </h1>
              <p className="font-secondary text-palette-light text-base md:text-lg lg:text-xl">
                Making it easy to switch shifts with your coworkers.
              </p>
              <button className="bg-blue-600 text-white font-bold py-2 px-6 rounded-2xl">
                <a href="/auth/login" className="button">
                  Login
                </a>
              </button>
            </div>
          </div>
        </div>
        <FooterComponent />
      </main>
    </>
  );
}

export default IndexPage;
