import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Sidebar from "@/components/Sidebar";
import UploadButton from "@/components/UploadButton";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [selectedFiles, setSelectedFiles] = useState([]);

  const saveFiles = async (files) => {
    try {
      await fs.ensureDir("./mike"); // Cria a pasta ./mike se ela não existir
      files.forEach(async (file) => {
        await fs.copy(file.path, `./mike/${file.name}`); // Copia o arquivo para a pasta ./mike
      });
      console.log("Arquivos salvos com sucesso!");
    } catch (err) {
      console.error(err);
    }
  };

  const handleFilesSelect = (files) => {
    setSelectedFiles((prevSelectedFiles) => [...prevSelectedFiles, ...files]);
  };

  const handleGenerateClick = () => {
    console.log(selectedFiles);
  };
  return (
    <>
      <Head>
        <title>Switch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar />

        <div className="flex flex-col p-4 h-screen justify-center bg-slate-200 sm:ml-64">
          <div className="flex flex-row">
            <span className="mb-4 text-2xl font-bold">Upload File</span>
            <div className="flex flex-row ml-auto">
              <button
                type="button"
                className="inline-flex items-center px-4 py-2 text-sm mb-4 font-medium text-white bg-blue-600 border border-transparent rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                onClick={handleGenerateClick}
              >
                Generate
              </button>
            </div>
          </div>

          <div className="ml-auto mr-auto w-full p-4 border-2 border-black border-dashed rounded-lg dark:border-gray-700">
            <div className="flex items-center justify-center h-96 rounded bg-gray-50 dark:bg-gray-800">
              <UploadButton onFilesSelect={handleFilesSelect} />
              {/*}
                <svg
                  className="w-12 h-12 mx-auto text-gray-400"
                  stroke="currentColor"
                  fill="none"
                  viewBox="0 0 48 48"
                  aria-hidden="true"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M12 8v28a4 4 0 004 4h20a4 4 0 004-4V8a4 4 0 00-4-4H16a4 4 0 00-4 4z"
                  ></path>
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M16 12h16m-16 4h16m-7 4h7m-7 4h7m-16 4h16"
                  ></path>
                </svg>

                <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">
                  <button
                    type="button"
                    className="font-medium text-blue-600 hover:text-blue-500 dark:text-blue-400 dark:hover:text-blue-300 focus:outline-none focus:underline transition ease-in-out duration-150"
                  >
                    Upload a file
                  </button>{" "}
                  or drag and drop
                </p>
                <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                  All pdf, doc, csv, xlsx types are supported
                </p>
                */}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
